[package]
name = "master_backend"
version = "0.1.0"
authors = ["Jonas Körner <jkoerner@odd-it.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
